POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "me",
  "password": "password",
  "role": "teacher"
}

###
POST http://localhost:3001/api/users/me/courses
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWUiLCJpZCI6IjYzZGVkZmU3NzUyODc4MjIyMDg4MmUwMCIsImlhdCI6MTY3NTU1NzkxNH0.8axodjQ9uE5WIm2xh-Jp0rT4AMahuVvpz3LIMvQ_JZk
Content-Type: application/json

{
  "username": "me",
  "password": "password",
  "role": "teacher",
}